- id: PLUMgrid-Gateway
  type: group
  role: [PLUMgrid-Gateway]
  tasks: [hiera, globals, logging, tools, netconfig]
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

# Skip default neutron plugins
- id: primary-openstack-network-plugins-l2
  type: skipped
- id: openstack-network-plugins-l2
  type: skipped
- id: openstack-network-routers-ha
  type: skipped
# Skip Neutron agents
- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: primary-openstack-network-agents-dhcp
  type: skipped
- id: openstack-network-agents-dhcp
  type: skipped
- id: primary-openstack-network-agents-metadata
  type: skipped
- id: openstack-network-agents-metadata
  type: skipped
- id: openstack-network-agents-sriov
  type: skipped
# Skip default fuel networks and routers
- id: openstack-network-networks
  type: skipped
- id: openstack-network-routers
  type: skipped

- id: disable-ovs
  groups: ['controller', 'compute', 'PLUMgrid-Gateway', 'primary-controller']
  required_for: [netconfig]
  requires: [deploy_start, globals]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/disable_ovs.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: pgtools-support
  groups: ['controller', 'primary-controller']
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/tools.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000

- id: check-pgzone
  groups: ['controller', 'compute', 'PLUMgrid-Gateway', 'primary-controller']
  required_for: [post_deployment_end, pg_common]
  requires: [post_deployment_start]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/pre_deployment.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720

- id: pg_common
  groups: ['controller', 'compute', 'PLUMgrid-Gateway', 'primary-controller']
  required_for: [post_deployment_end, setup-director]
  requires: [post_deployment_start, check-pgzone]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/pg_common.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000

- id: setup-director
  groups: ['controller', 'primary-controller']
  required_for: [post_deployment_end, director-fixes]
  requires: [post_deployment_start, pg_common]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/director.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000

- id: director-fixes
  groups: ['controller', 'primary-controller']
  required_for: [post_deployment_end, post_pg_license]
  requires: [post_deployment_start, setup-director]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/director_fixes.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000

- id: post_pg_license
  role: ['primary-controller']
  required_for: [post_deployment_end, solution-api]
  requires: [post_deployment_start, director-fixes]
  type: shell
  parameters:
    cmd: bash post_pg_license.sh
    timeout: 3000

- id: solution-api
  role: ['primary-controller']
  required_for: [post_deployment_end, setup-edge, setup-gateway]
  requires: [post_deployment_start, post_pg_license]
  type: shell
  parameters:
    cmd: bash solution_api.sh
    timeout: 3000

- id: setup-edge
  groups: ['compute']
  required_for: [post_deployment_end]
  requires: [post_deployment_start, solution-api, pg_common]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/edge.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000

- id: setup-gateway
  groups: ['PLUMgrid-Gateway']
  required_for: [post_deployment_end]
  requires: [post_deployment_start, solution-api, pg_common]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/gateway.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3000
