attributes:
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        message: "Please use Neutron with VLAN segmentation, the only network type supported with PLUMgrid plugin."
  plumgrid_username:
    value: "plumgrid"
    label: "Enter the username for PLUMgrid"
    description: "Enter the default username for accessing PLUMgrid"
    weight: 25
    type: "text"
    regex:
      source: '^\S+$'
      error: "username cannot be empty or contain spaces"
  plumgrid_password:
    value: "plumgrid"
    label: "Enter the password for PLUMgrid"
    description: "Enter the default password for accessing PLUMgrid"
    weight: 26
    type: "password"
    regex:
      source: '^\S+$'
      error: "password cannot be empty or contain spaces"
  plumgrid_package_repo:
    value: ''
    label: 'Repository for PLUMgrid packages'
    description: 'The IP address for PLUMgrid LCM'
    weight: 45
    type: "text"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
  plumgrid_zone:
    value: ""
    label: "Enter the zone name for PLUMgrid LCM"
    description: "Enter the zone name configured on the PLUMgrid LCM"
    weight: 55
    type: "text"
    regex:
      source: '^\S+$'
      error: "Zone name cannot be empty or contain spaces"
  plumgrid_license:
    value: ""
    label: "Enter the license for PLUMgrid"
    description: "Enter the license that will be used by the PLUMgrid platform"
    weight: 65
    type: "text"
    regex:
      source: '^\S+$'
      error: "License field cannot be empty or contain spaces"
  gateway_devs:
    value: ""
    label: "Enter the interface(s) to be used by GW"
    description: "Provide comma separated interfaces that will be used for external connectivity by the PLUMgrid gateway (eg. eth3,eth4)"
    weight: 75
    type: "text"
    regex:
      source: '^(\S+,?\s*)+$'
      error: "One or more comma seperated gateway interfaces must be entered (eg. eth3,eth4)"
  plumgrid_virtual_ip:
    value: ''
    label: 'PLUMgrid VIP to access the PLUMgrid console'
    description: 'The IP address for PLUMgrid console'
    weight: 30
    type: "text"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
  plumgrid_fabric_network:
    value: ''
    label: 'Enter the PLUMgrid Fabric Network'
    description: 'Enter the network that will be used by PLUMgrid Fabric (no need to enter subnet)'
    weight: 32
    type: "text"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
